#!/usr/bin/env node
/**
 * Generates `e2e/scenarios-index.md`: one row per scenario declared in a `.cases.md` Summary table,
 * grouped by level (the filename suffix) and module (its directory under `e2e/`).
 *
 * `pnpm scenarios:index` writes the file. `node scripts/scenarios-index.mjs check` — used by
 * `PR-API-07` in `e2e/process/process.api.spec.ts` — regenerates it in memory and fails if the file
 * on disk differs. The file is **never hand-edited**: a hand-maintained list of case IDs is exactly
 * what `FX-031` is the ledger entry for (the Cases column of `docs/api-contract.md` cited case IDs
 * that did not exist). Running the generator again is the only fix for a stale index.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const OUTPUT = 'e2e/scenarios-index.md';

const SKIP_DIRS = new Set([
  '.git',
  '.next',
  'blob-report',
  'coverage',
  'dist',
  'node_modules',
  'playwright-report',
  'test-results',
]);

/** Filename suffix decides the level, exactly the way it decides the Playwright project. */
const LEVEL_BY_SUFFIX = [
  ['.unit.cases.md', 'unit'],
  ['.api.cases.md', 'api'],
  ['.functional.cases.md', 'functional'],
  ['.integration.cases.md', 'integration'],
];

/** First cell of a Summary table row is the ID, the second the title — backticks optional. */
const SUMMARY_ROW = /^\|\s*`?([A-Z]{2,5}-(?:API|FN|UT|INT)-\d{2,3})`?\s*\|\s*([^|]+?)\s*\|/;

function repoRoot() {
  let dir = process.cwd();

  for (;;) {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error('Monorepo root not found (pnpm-workspace.yaml)');
    }
    dir = parent;
  }
}

function walk(rootDir, relDir, acc = []) {
  const abs = join(rootDir, relDir);
  if (!existsSync(abs)) {
    return acc;
  }

  for (const entry of readdirSync(abs, { withFileTypes: true })) {
    const rel = relDir === '' ? entry.name : `${relDir}/${entry.name}`;
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) {
        walk(rootDir, rel, acc);
      }
      continue;
    }
    acc.push(rel);
  }

  return acc;
}

function caseDocs(root) {
  return walk(root, 'e2e')
    .filter((file) => file.endsWith('.cases.md'))
    .sort();
}

function levelOf(file) {
  for (const [suffix, level] of LEVEL_BY_SUFFIX) {
    if (file.endsWith(suffix)) {
      return level;
    }
  }
  return 'other';
}

function moduleOf(file) {
  return dirname(file).replace(/^e2e\/?/, '') || '(root)';
}

/** Every scenario declared in a Summary table, across every `.cases.md` in `e2e/`. */
function scenarios(root) {
  const rows = [];

  for (const doc of caseDocs(root)) {
    const level = levelOf(doc);
    const module = moduleOf(doc);
    const content = readFileSync(join(root, doc), 'utf8');

    for (const line of content.split(/\r?\n/)) {
      const match = SUMMARY_ROW.exec(line);
      if (match !== null) {
        rows.push({ level, module, id: match[1], title: match[2].trim() });
      }
    }
  }

  return rows;
}

function render(rows) {
  const lines = [
    '# Scenario index',
    '',
    '**Generated by `pnpm scenarios:index`. Do not edit by hand** — run the command again after',
    'changing any `.cases.md`; `PR-API-07` fails `pnpm verify` when this file is stale.',
    '',
    'One row per scenario declared in a Summary table, across every level and module under `e2e/`.',
    '',
    '| Level | Module | ID | Title |',
    '| ----- | ------ | -- | ----- |',
    ...rows.map(
      ({ level, module, id, title }) => `| ${level} | ${module} | \`${id}\` | ${title} |`,
    ),
    '',
  ];

  return lines.join('\n');
}

const root = repoRoot();
const mode = process.argv[2] ?? 'write';
const rows = scenarios(root);
const content = render(rows);

if (mode === 'check') {
  const outputPath = join(root, OUTPUT);
  const onDisk = existsSync(outputPath) ? readFileSync(outputPath, 'utf8') : null;

  if (onDisk !== content) {
    console.error(
      `${OUTPUT} is stale or missing. Run \`pnpm scenarios:index\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log(`${OUTPUT} is current (${rows.length} scenarios).`);
} else {
  writeFileSync(join(root, OUTPUT), content, 'utf8');
  console.log(`Wrote ${OUTPUT} (${rows.length} scenarios).`);
}
